### ISSUE TITLE
Correct Travis Build again

### ISSUE THREAD

**Issue by thomasletsch** [bisdk/sdk#12]
Apparently the travis build is broken. We have the RealGatewayTest JUnit test not marked as ignored.
Normally I would just ignore it again, but we should keep it executable for others to have a simple test against their real BiSecure Gateway (see #7 ). 
Perhaps a renaming can help...

**Comment by yogitea** [comment]
RealGateWay Test does not complete successfully for me.

It ends with while: Sending package command: Command(code=112 (70), name='HM_GET_TRANSITION')


Gradle Test Executor 1 finished executing tests.

> Task :jvmTest FAILED

org.bisdk.sdk.RealGatewayTest[jvm] > testStartup[jvm] FAILED
    java.lang.IllegalStateException: Retry failed: Received Exception Timeout waiting for PackageReceived (after waiting 5000 ms)
        at org.bisdk.sdk.ClientAPI.sendWithRetry(ClientAPI.kt:277)
        at org.bisdk.sdk.ClientAPI.getTransition(ClientAPI.kt:192)
        at org.bisdk.sdk.RealGatewayTest.testStartup(RealGatewayTest.kt:42)

4 tests completed, 1 failed, 3 skipped
Finished generating test XML results (0.026 secs) into: /home/chr/sdk/build/test-results/jvmTest
Generating HTML test report...
Finished generating test html results (0.04 secs) into: /home/chr/sdk/build/reports/tests/jvmTest
:jvmTest (Thread[Daemon worker,5,main]) completed. Took 14.833 secs.

FAILURE: Build failed with an exception.

**Comment by warting** [comment]
Could do something like this?
https://github.com/bisdk/sdk/pull/14
