### ISSUE TITLE
Odd Behavior

### ISSUE THREAD

**Issue by yogitea** [bisdk/sdk#13]
@thomasletsch I experience some odd behavior and would like to know if you have any more knowledge on why it happens and how to avoid it.

1. SET_STATE is giving me PERMISSION DENIED errors. As far as I can tell the user I has the rights to the group and device.
Any hint on how to debut this further?

2. After a while my login requests are immediately followed by Logout responses. Any idea why this is the case? In my experience only waiting will fix this.

In case you have the info I will again document it for everybody else! Thank you.

**Comment by yogitea** [comment]
To clarify. I getting the same permission denied in both implementations. So I am guessing it might have something to do with my Gateway and how that is setup?!

**Comment by thomasletsch** [comment]
Can you post the debug log? There we should see more information of exactly what is returned after which call.
For the LOGOUTS: Are you sure that the user you are using for running the tests is only used there and not the same as in the app? If not, we have to dig deeper in the log files...

**Comment by yogitea** [comment]
I had given up on implementing this and instead used an ESP with Tasmota that "press" the buttons of the original remote.  This does not give me a feedback, but allows me to open the door reliably for the last 2 years.
